<?php

/**
 * This configuration cache file was generated by Laminas\ConfigAggregator\ConfigAggregator
 * at 2022-11-07T11:43:54+00:00
 */
return [
    'dependencies' => [
        'invokables' => [
            'Mezzio\\Helper\\ServerUrlHelper' => 'Mezzio\\Helper\\ServerUrlHelper',
            'Mezzio\\Helper\\Template\\TemplateVariableContainerMiddleware' => 'Mezzio\\Helper\\Template\\TemplateVariableContainerMiddleware',
            'Psr\\Http\\Message\\RequestFactoryInterface' => 'Laminas\\Diactoros\\RequestFactory',
            'Psr\\Http\\Message\\ResponseFactoryInterface' => 'Laminas\\Diactoros\\ResponseFactory',
            'Psr\\Http\\Message\\StreamFactoryInterface' => 'Laminas\\Diactoros\\StreamFactory',
            'Psr\\Http\\Message\\ServerRequestFactoryInterface' => 'Laminas\\Diactoros\\ServerRequestFactory',
            'Psr\\Http\\Message\\UploadedFileFactoryInterface' => 'Laminas\\Diactoros\\UploadedFileFactory',
            'Psr\\Http\\Message\\UriFactoryInterface' => 'Laminas\\Diactoros\\UriFactory',
            'App\\Handler\\PingHandler' => 'App\\Handler\\PingHandler'
        ],
        'factories' => [
            'Mezzio\\Helper\\ServerUrlMiddleware' => 'Mezzio\\Helper\\ServerUrlMiddlewareFactory',
            'Mezzio\\Helper\\UrlHelper' => 'Mezzio\\Helper\\UrlHelperFactory',
            'Mezzio\\Helper\\UrlHelperMiddleware' => 'Mezzio\\Helper\\UrlHelperMiddlewareFactory',
            'Mezzio\\Router\\FastRouteRouter' => 'Mezzio\\Router\\FastRouteRouterFactory',
            'Mezzio\\Application' => 'Mezzio\\Container\\ApplicationFactory',
            'Mezzio\\ApplicationPipeline' => 'Mezzio\\Container\\ApplicationPipelineFactory',
            'Laminas\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Mezzio\\Container\\EmitterFactory',
            'Laminas\\Stratigility\\Middleware\\ErrorHandler' => 'Mezzio\\Container\\ErrorHandlerFactory',
            'Mezzio\\Handler\\NotFoundHandler' => 'Mezzio\\Container\\NotFoundHandlerFactory',
            'Mezzio\\MiddlewareContainer' => 'Mezzio\\Container\\MiddlewareContainerFactory',
            'Mezzio\\MiddlewareFactory' => 'Mezzio\\Container\\MiddlewareFactoryFactory',
            'Mezzio\\Middleware\\ErrorResponseGenerator' => 'Mezzio\\Container\\ErrorResponseGeneratorFactory',
            'Laminas\\HttpHandlerRunner\\RequestHandlerRunner' => 'Mezzio\\Container\\RequestHandlerRunnerFactory',
            'Psr\\Http\\Message\\ResponseInterface' => 'Mezzio\\Container\\ResponseFactoryFactory',
            'Mezzio\\Response\\ServerRequestErrorResponseGenerator' => 'Mezzio\\Container\\ServerRequestErrorResponseGeneratorFactory',
            'Psr\\Http\\Message\\ServerRequestInterface' => 'Mezzio\\Container\\ServerRequestFactoryFactory',
            'Psr\\Http\\Message\\StreamInterface' => 'Mezzio\\Container\\StreamFactoryFactory',
            'Mezzio\\Router\\Middleware\\DispatchMiddleware' => 'Mezzio\\Router\\Middleware\\DispatchMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\ImplicitHeadMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitHeadMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\MethodNotAllowedMiddleware' => 'Mezzio\\Router\\Middleware\\MethodNotAllowedMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\RouteMiddleware' => 'Mezzio\\Router\\Middleware\\RouteMiddlewareFactory',
            'Mezzio\\Router\\RouteCollector' => 'Mezzio\\Router\\RouteCollectorFactory',
            'App\\Handler\\HomePageHandler' => 'App\\Handler\\HomePageHandlerFactory'
        ],
        'aliases' => [
            'Mezzio\\Router\\RouterInterface' => 'Mezzio\\Router\\FastRouteRouter',
            'Zend\\Expressive\\Router\\RouterInterface' => 'Mezzio\\Router\\RouterInterface',
            'Zend\\Expressive\\Router\\FastRouteRouter\\FastRouteRouter' => 'Mezzio\\Router\\FastRouteRouter',
            'Mezzio\\Delegate\\DefaultDelegate' => 'Mezzio\\Handler\\NotFoundHandler',
            'Mezzio\\Middleware\\DispatchMiddleware' => 'Mezzio\\Router\\Middleware\\DispatchMiddleware',
            'Mezzio\\Middleware\\ImplicitHeadMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitHeadMiddleware',
            'Mezzio\\Middleware\\ImplicitOptionsMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddleware',
            'Mezzio\\Middleware\\NotFoundMiddleware' => 'Mezzio\\Handler\\NotFoundHandler',
            'Mezzio\\Middleware\\RouteMiddleware' => 'Mezzio\\Router\\Middleware\\RouteMiddleware',
            'Laminas\\HttpHandlerRunner\\RequestHandlerRunnerInterface' => 'Laminas\\HttpHandlerRunner\\RequestHandlerRunner',
            'Zend\\Expressive\\Application' => 'Mezzio\\Application',
            'Zend\\Expressive\\ApplicationPipeline' => 'Mezzio\\ApplicationPipeline',
            'Zend\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Laminas\\HttpHandlerRunner\\Emitter\\EmitterInterface',
            'Zend\\Stratigility\\Middleware\\ErrorHandler' => 'Laminas\\Stratigility\\Middleware\\ErrorHandler',
            'Zend\\Expressive\\Handler\\NotFoundHandler' => 'Mezzio\\Handler\\NotFoundHandler',
            'Zend\\Expressive\\MiddlewareContainer' => 'Mezzio\\MiddlewareContainer',
            'Zend\\Expressive\\MiddlewareFactory' => 'Mezzio\\MiddlewareFactory',
            'Zend\\Expressive\\Middleware\\ErrorResponseGenerator' => 'Mezzio\\Middleware\\ErrorResponseGenerator',
            'Zend\\HttpHandlerRunner\\RequestHandlerRunner' => 'Laminas\\HttpHandlerRunner\\RequestHandlerRunner',
            'Zend\\Expressive\\Response\\ServerRequestErrorResponseGenerator' => 'Mezzio\\Response\\ServerRequestErrorResponseGenerator',
            'Zend\\Expressive\\Router\\Middleware\\DispatchMiddleware' => 'Mezzio\\Router\\Middleware\\DispatchMiddleware',
            'Zend\\Expressive\\Router\\Middleware\\ImplicitHeadMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitHeadMiddleware',
            'Zend\\Expressive\\Router\\Middleware\\ImplicitOptionsMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddleware',
            'Zend\\Expressive\\Router\\Middleware\\MethodNotAllowedMiddleware' => 'Mezzio\\Router\\Middleware\\MethodNotAllowedMiddleware',
            'Zend\\Expressive\\Router\\Middleware\\RouteMiddleware' => 'Mezzio\\Router\\Middleware\\RouteMiddleware',
            'Zend\\Expressive\\Router\\RouteCollector' => 'Mezzio\\Router\\RouteCollector'
        ]
    ],
    'config_cache_path' => 'data/cache/config-cache.php',
    'laminas-diactoros' => [
        'x-forwarded-request-filter' => [
            'trusted-proxies' => '',
            'trusted-headers' => []
        ]
    ],
    'templates' => [
        'paths' => [
            'app' => [
                'templates/app'
            ],
            'error' => [
                'templates/error'
            ],
            'layout' => [
                'templates/layout'
            ]
        ]
    ],
    'config_cache_enabled' => true,
    'debug' => false,
    'mezzio' => [
        'error_handler' => [
            'template_404' => 'error::404',
            'template_error' => 'error::error'
        ]
    ]
];

