<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?=$this->headTitle('MitfahrerDB')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .navbar-brand { padding: 0; }
        .navbar-brand img { margin: -.5rem 0; object-fit:contain; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm bg-white fixed-top" role="navigation" style="Border-bottom: 1px solid lightblue">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('login.get')?>">
                    <img width="200" height="60" src="https://www.gso-koeln.de/wp-content/uploads/2020/06/cropped-LOGO-GSO_neu.png" class="custom-logo" alt="Georg-Simon-Ohm-Berufskolleg">
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?=$this->url('register.get')?>" class="nav-link text-dark">
                                 Registrieren
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?=$this->url('login.get')?>" class="nav-link text-dark">
                                Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?=$this->url('password')?>" class="nav-link text-dark">
                                Passwort vergessen
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?=$this->url('handbuch')?>" class="nav-link text-dark">
                                Handbuch
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                 &copy; <?=date('Y')?> <a href="https://www.gso-koeln.de">GSO</a> Georg-Simon-Ohm Berufskolleg.
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>
