<?php $this->layout('layout::default', ['title' => 'agb']) ?>
<html><head>
    <title>AGBs</title>
</head>
<body>
<h2>ALLGEMEINE NUTZUNGSBEDINGUNGEN (AGB)</h2>
<p></p>
<h2>ÜBER UNS</h2>
<div style="text-indent:20px">Die MitfahrerDB ist eine Web-Applikation zur Vermittlung von Schüler*innen und
    Lehrer*innen um Fahrgemeinschaften zu Bilden. Diese Anwendung ist im Zuge eines
    Oberstufenprojektes entstanden und ist nur von Schüler*innen und Lehrer*innen des
    Georg-Simon-Ohm Berufskolleg zu benutzen. </div>
<p></p>
<h2>DEFINITION</h2>
<div style="text-indent:20px">
    <p>„MitfahrerDB“ beschreibt hier die Web-Applikation, um die es sich im Folgenden
        handelt.</p>
    <p>„GSO“ beschreibt im Folgenden das Georg-Simon-Ohm Berufskolleg</p>
</div>
<h2>BEDINGUNGEN</h2>
<div style="text-indent:20px">
    <p></p><h3>1. Nutzung</h3><p></p>
    <div style="text-indent:25px"><p>1.1	Die Nutzung ist nur Schüler*innen und Lehrer*innen der GSO gestatten, diese
            sollen sich mit der von der GSO zur Verfügung gestellten E-Mailadresse
            anmelden.</p>
        <p>1.2 Andere E-Mailadressen sind nicht vorgesehen für die Registrierung und
            funktionieren dementsprechend auch nicht.</p>
        <p>1.3 Der/Die Nutzer*in erklärt sich hiermit einverstanden, E-Mails von der
            MitfahrerDB zu empfangen.</p>
    </div>
    <p></p><h3>2. Datenverwaltung</h3><p></p>
    <div style="text-indent:25px"><p>2.1	Die angegebenen Daten werden im Sinne der Nutzung der MitfahrerDB
            gespeichert.</p>
        <p>2.2	Die angegebenen Daten werden nicht an dritte weitergegeben.</p>
        <p>2.3	Der/Die Nutzer*in erklärt sich hiermit einverstanden, dass im Zuge des
            E-Mail-Verkehrs die E-Mailadresse an andere Nutzer*innen weitergegeben wird.</p>
    </div>
    <p></p><h3>3. Haftung</h3><p></p>
    <div style="text-indent:25px"><p>3.1 Die MitfahrerDB stellt nur den Kontakt zwischen den Nutzer*innen her und
            bürgt zu keinem Zeitpunkt für nicht eingehaltene Absprachen von Fahrten.</p>
        <p>3.2 Die MitfahrerDB übernimmt keine Verantwortung über die Preisverhandlung
            und geht nicht abgegebenen Zahlungen auch nicht nach.</p>
        <p>3.3 Wenn keine E-Mail bei, von der/dem Fahrtenersteller*in, geänderter oder
            gelöschter Fahrt gesendet oder Empfangen wurde, haftet hier die
            MitfahrerDB nicht.</p>
        <p>3.4	Der Gesetzgeber versichert sie während der Fahrt nur auf direktem Wege von
            der Schule und Heimat und umgekehrt.</p><p> Da es auf einer Fahrt mit mehreren
            Leuten auch zu Umwegen kommen kann, bestätigen wir hier nochmal
            ausdrücklich das die MitfahrerDB den/die Nutzer*innen zu keinem Zeitpunkt
            versichert.</p>
    </div>
</div></body></html>
