<?php $this->layout('layout::default', ['title' => 'agb']) ?>
<head>
    <title>AGBs</title>
</head>
<body>
<h2>ALLGEMEINE NUTZUNGSBEDINGUNGEN (AGB)</h2>
<p></p>
<h2>ÜBER UNS</h2>
<div style="text-indent:20px">Die MitfahrerDB ist eine Web-Applikation zur Vermittlung von Schüler*innen und
    Lehrer*innen um Fahrgemeinschaften zu Bilden. Diese Anwendung ist im Zuge eines
    Oberstufenprojektes entstanden und ist nur von Schüler*innen und Lehrer*innen des
    Georg-Simon-Ohm Berufskolleg zu benutzen. </div>
<p></p>
<h2>DEFINITION</h2>
<div style="text-indent:20px">
    <p>„MitfahrerDB“ beschreibt hier die Web-Applikation, um die es sich im Folgenden
        handelt.</p>
    <p>„GSO“ beschreibt im Folgenden das Georg-Simon-Ohm Berufskolleg</p>
</div>
<h2>BEDINGUNGEN</h2>
<div style="text-indent:20px">
    <p><h3>1. Nutzung</h3></p>
    <div style="text-indent:5px"></div>
</div>
