<?php $this->layout('layout::authenticated', ['title' => 'Board']) ?>
<div class="container">
    <div class="row">
        <h1>Hier sehen sie alle verfügbaren Fahrten</h1>
    </div>
    <?php
    $url = $this->url('board.post');
    $board = $this->url('board');
    echo '<form style="width: 12rem;" action="' . $url . '" method="post">
<div class="form-group">
        <label for="raucher">Raucher</label>
        <input type="radio" id="raucher" name="bRaucher" value="1">Ja</input>
        <input type="radio" id="raucher" name="bRaucher" value="0">Nein</input>
    </div>
    <div class="form-group">
        <label for="tierhaare">Tierhaare</label>
        <input type="radio" id="tierhaare" name="bTierhaare" value="1">Ja</input>
        <input type="radio" id="tierhaare" name="bTierhaare" value="0">Nein</input>
    </div>
    <div class="form-group">
        <label for="maskenpflicht">Maskenpflicht</label>
        <input type="radio" id="maskenpflicht" name="bMaskenpflicht" value="1">Ja</input>
        <input type="radio" id="maskenpflicht" name="bMaskenpflicht" value="0">Nein</input>
    </div>
    <div class="form-group">
        <label for="geschlecht">Geschlecht</label>
        <input type="radio" id="geschlechtM" name="bGeschlecht" value="M">M</input>
        <input type="radio" id="geschlechtW" name="bGeschlecht" value="W">W</input>
        <input type="radio" id="geschlechtD" name="bGeschlecht" value="D">D</input>
    </div>
        <div class="pt-1 mb-4">
            <button type="submit" class="btn btn-primary btn-lg">Filter Anwenden</button>
        </div>
    </form>
    <button>
    <a href="'. $board .'" class="nav-link text-dark">
                                 Filter Zurücksetzen
                            </a>
                            </button>'
    ?>
    <table class="table table-hover">
        <?php
        try {
            if ($rides !== null) {
                foreach ($rides as $ride) {
                    $email = $ride['email'];
                    echo '<tr>';
                    echo '<td>' . $email . '</td>';
                    echo '<td>' . $ride['dDatumUhrzeit'] . '</td>';
                    echo '<td>' . $ride['cStartOrt'] . '</td>';
                    echo '<td>' . $ride['cZielOrt'] . '</td>';
                    echo '<td>' . $ride['freieSitzplaetze'] . '</td>';
                    echo '<td>' . $ride['nPreis'] . 'EUR <br>' . '</td>';
                    if ($email === $ride['sessionEmail']) {
                        $url = $this->url('delete.post');
                        echo '<td> 
                    <form style="width: 12rem;" action="' . $url . '" method="post">
                    <input type="hidden" name="rideId" value="' . $ride['kID'] . '">
                    <div class="pt-1 mb-4">
                        <button type="submit" class="btn btn-primary btn-lg">Fahrt löschen</button>
                    </div>
                    </form>
                    </td>';
                    } else {
                        $url = $this->url('join.post');
                        echo '<td> 
                    <form style="width: 12rem;" action="' . $url . '" method="post">
                    <input type="hidden" name="rideId" value="' . $ride['kID'] . '">
                    <div class="pt-1 mb-4">
                        <button type="submit" class="btn btn-primary btn-lg">Fahrt beitreten</button>
                    </div>
                    </form>
                    </td>';
                    }
                    echo '</tr>';
                }
            }
        } catch (Exception $exception) {
            var_dump($exception);
        }
        ?>
    </table>
</div>
