<?php $this->layout('layout::authenticated', ['title' => 'ride.get']) ?>
<form action="<?= $this->url('ride.post') ?>" method="post">
    <?php if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $this->escapeHtml($error) ?>
        </div>
    <?php endif ?>
    <div class="form-group">
        <label for="start">Start</label>
        <input type="text" class="form-control" required="required" id="start" name="start" placeholder="Startort">
    </div>
    <div class="form-group">
        <label for="ziel">Ziel</label>
        <input type="text" class="form-control" required="required" id="ziel" name="ziel" placeholder="Zielort">
    </div>
    <div class="form-group">
        <label for="plaetze">Sitzplätze</label>
        <input type="number" class="form-control" required="required" id="plaetze" name="plaetze"
               placeholder="Sitzplätze">
    </div>
    <div class="form-group">
        <label for="preis">Preis</label>
        <input type="number" class="form-control" required="required" id="preis" name="preis" placeholder="Preis in Euro">
    </div>
    <div class="form-group">
        <label for="date">Datum</label>
        <input type="date" id="date" name="date">
    </div>
    <div class="form-group">
        <label for="time">Uhrzeit</label>
        <input type="time" id="time" name="time">
    </div>
    <button type="submit" class="btn btn-primary">Speichern</button>
</form>
