<?php $this->layout('layout::authenticated', ['title' => 'logged-handbuch']) ?>
<h1>Benutzerhandbuch für die Mitfahrer-Datenbank</h1>

<p>Damit Sie unsere Web-Anwendung ohne Probleme benutzen können, folgen Sie den nächsten Schritten:  

Sie finden die verschiedenen Ansichten unter den Reitern, die im obigen Teil des Bildschirms zu sehen sind.</p>

<div style="text-indent:5px"><h3>1. Rufen Sie die Web-Anwendung auf</h3></div>

<p>Die Homepage der Web-Anwendung erreichen Sie, wenn Sie in den Browser die richtige UML eingeben.
Sie ist identisch zu der Web-Ansicht unter dem Reiter „Login“.
Hier könnten Sie sich einloggen unter der Bedingung, dass Sie sich vorher schon einmal registriert haben. </p>


<div style="text-indent:5px"><h3>2. Die Registrierung</h3></div>

<p>Bei dieser Ansicht können Sie sich registrieren.
Bedenken Sie, dass nur E-Mail-Adressen der GSO zugelassen werden und alle Felder ausgefüllt werden müssen.
Es ist ein mindestens 8 Zeichen langes Passwort zu empfehlen, aber keine Pflicht.
Es liegt in Ihrer Verantwortung ein sicheres Passwort zu vergeben. </p>


<div style="text-indent:5px"><h3>3. Profil</h3></div>

<p>Nach dem Login erhalten Sie Zugriff auf Ihr Profil. In Ihrem Profil können Sie Informationen über sich eingeben, damit die Mitfahrer wissen, ob Sie z.B. Rauchen oder Tierhaare im Auto vorzufinden sind. 
Außerdem können Sie eventuelle Treffpunkte oder sonstige Informationen in einem Textfeld hinterlegen.
Die Infofelder sind freiwillig auszufüllen. </p>

<div style="text-indent:5px"><h3>4. Fahrten posten</h3></div>

<p>Wenn Sie eingeloggt sind, können Sie Fahrten auf dem Dashboard posten, um Fahrgemeinschaften zu bilden. </p>
Hier ist zu beachten, dass alle Felder ausgefüllt sein müssen, um eine Fahrt auf dem Dashboard zu posten und, dass nur freie Sitzplätze angegeben werden, sprich ohne Fahrersitz.

<div style="text-indent:5px"><h3>5. Passwort vergessen</h3></div>

<p>Wenn Sie Ihr Passwort vergessen haben, können Sie ganz simpel ihre E-Mail der GSO eingeben mit der Sie sich anmelden würden und auf „Passwort vergessen“ klicken. Daraufhin wird Ihnen ein neues Passwort per Mail geschickt, welches Sie dann verwenden können. </p>

<div style="text-indent:5px"><h3>6. Dashboard</h3></div>

<p>In dieser Ansicht können Sie Fahrten filtern und buchen. Nach dem Buchen einer Fahrt werden Sie als Mitfahrer registriert.
Wenn der Filter zurückgesetzt werden soll, finden Sie dazu ebenfalls einen Button. </p>
