<?php $this->layout('layout::default', ['title' => 'Login.get']) ?>
<section class="vh-80">
    <div class="container-fluid">
		<form style="width: 50rem;" action="<?= $this->url('login.post') ?>" method="post">
			<div class="row ">
				<div class="col-sm-6 text-black">
                    <?php if (isset($error)) : ?>
                        <div class="alert alert-danger" role="alert">
                            <?= $this->escapeHtml($error) ?>
                        </div>
                    <?php endif ?>
            
                
                <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 2px;">Login</h3>
                    <div class="form-outline mb-4">
                        <label for="username">Email</label>
                        <input type="text" class="form-control form-control-lg" id="email" name="email" placeholder="Benutzerkonto angeben">
                    </div>

                    <div class="form-outline mb-4">
                        <label for="password">Passwort</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Passwort">
                    </div>

                

                    <div class="pt-1 mb-4">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Anmelden</button>
                    </div>

                        <p class="small mb-5 pb-lg-2"><a class="text-muted" href="<?=$this->url('password')?>">Passwort vergessen?</a></p>
                        <p>Noch keinen Account? <a href="<?=$this->url('register.get')?>">hier Registrieren</a></p>
        </form>
				</div>
            <div class="col-sm-6 px-0 d-none d-sm-block">
                <video id="wp-custom-header-video" autoplay="" loop="" playsinline="" style="" width="700" id="vid" height="535" src="https://www.gso-koeln.de/wp-content/uploads/2020/11/20201106_GSO-Loop_Herbst-Impressionen_1920x900.mp4" type="video/mp4"></video>
                <alt="Login image class="w-200 vh-200" style="object-fit: cover; object-position: left;">
            </div>
                <script>
                    document.getElementById('vid').play();
                </script>
			</div>
	</div>
</section>  
