<?php $this->layout('layout::default', ['title' => 'login.get']) ?>
<form action="<?= $this->url('login.post') ?>" method="post">
    <?php if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $this->escapeHtml($error) ?>
        </div>
    <?php endif ?>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" required="required" id="email" name="email"
               placeholder="Enter email">
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" required="required" id="password" name="password"
               placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
