<?php $this->layout('layout::default', ['title' => 'Password']) ?>
<div class="container">
    <div class="row">
        <div class="col-sm"><form action="<?= $this->url('password') ?>" method="post">
                <?php if (isset($error)) : ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $this->escapeHtml($error) ?>
                    </div>
                <?php endif ?>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form></div>
    </div>
</div>
