<?php $this->layout('layout::default', ['title' => 'password']) ?>
<section class="vh-80">
    <div class="container" style="justify-content:center; display:flex;">
        <div class="row" >
            <div class="col-sm">
                    <form style="width: 25rem;" action="<?= $this->url('password') ?>" method="post">
                    <div class="col-sm-12 text-black">
                        <?php if (isset($error)) : ?>
                            <div class="alert alert-danger" role="alert">
                                <?= $this->escapeHtml($error) ?>
                            </div>
                        <?php endif ?>
                        <img hight="350" width="350" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/OOjs_UI_icon_lock-ltr-progressive.svg/1024px-OOjs_UI_icon_lock-ltr-progressive.svg.png" class="displayed" alt="Georg-Simon-Ohm-Berufskolleg">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="z.B.  max.m2@gso.schule.koeln">
                        </div>
                        <button type="submit" class="btn btn-danger btn-block">Passwort vergessen</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>  
