<?php $this->layout('layout::default', ['title' => 'register.get']) ?>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <form action="<?= $this->url('register.post') ?>" method="post">
                <?php if (isset($error)) : ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $this->escapeHtml($error) ?>
                    </div>
                <?php endif ?>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="email">Vorname</label>
                    <input type="text" class="form-control" id="vorname" name="vorname" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="email">Nachname</label>
                    <input type="text" class="form-control" id="nachname" name="nachname" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>

                <div class="form-group">
                    <label for="passwordRepeat">Password Wiederholen</label>
                    <input type="password" class="form-control" id="passwordRepeat" name="passwordRepeat"
                           placeholder="Password Repeat">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
