<?php $this->layout('layout::default', ['title' => 'register.get']) ?>
<form action="<?= $this->url('register.post') ?>" method="post">
    <?php if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $this->escapeHtml($error) ?>
        </div>
    <?php endif ?>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email" name="email" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="vorname">Vorname</label>
        <input type="text" class="form-control" id="vorname" name="vorname" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="nachname">Nachname</label>
        <input type="text" class="form-control" id="nachname" name="nachname" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>

    <div class="form-group">
        <label for="passwordRepeat">Password Wiederholen</label>
        <input type="password" class="form-control" id="passwordRepeat" name="passwordRepeat"
               placeholder="Password Repeat">
    </div>

    <button type="submit" class="btn btn-primary">Registrieren</button>
</form>
