<?php $this->layout('layout::default', ['title' => 'register.get']) ?>

    <div class="row" style="justify-content:center;">
        <div class="col-lg-4 col-lg-offset-4 center-block">

            <form action="<?= $this->url('register.post') ?>" method="post">
                <?php if (isset($error)) : ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $this->escapeHtml($error) ?>
                    </div>
                <?php endif ?>
                
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" required="required" id="email" name="email" placeholder="E-Mail Adresse angeben">
                </div>
                <div class="form-group">
                    <label for="vorname">Vorname</label>
                    <input type="text" class="form-control" required="required" id="vorname" name="vorname" placeholder="Vorname ">
                </div>
                <div class="form-group">
                    <label for="nachname">Nachname</label>
                    <input type="text" class="form-control" required="required" id="nachname" name="nachname" placeholder="Nachname">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" required="required" id="password" name="password" placeholder="Passwort">
                </div>

                <div class="form-group">
                    <label for="passwordRepeat">Password Wiederholen</label>
                    <input type="password" class="form-control" required="required" id="passwordRepeat" name="passwordRepeat"
                        placeholder="Passwort wiederholen">
                </div>

                <button type="submit" class="btn btn-primary btn-block  ">Registrieren</button>
            </form>
        </div>    
    </div>                

